repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint
        additional_dependencies: ["eslint-plugin-react"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.9.1
    hooks:
      - id: commitizen
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
